#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sinatra
Version  : 1.4.7
Release  : 8
URL      : https://rubygems.org/downloads/sinatra-1.4.7.gem
Source0  : https://rubygems.org/downloads/sinatra-1.4.7.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-protection
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-tilt

%description
# Sinatra
*æ³¨ï¼æ¬ææ¡£æ¯è±æççç¿»è¯ï¼åå®¹æ´æ°æå¯è½ä¸åæ¶ãå¦æä¸ä¸è´çå°æ¹ï¼è¯·ä»¥è±æçä¸ºåã*

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sinatra-1.4.7
gem spec %{SOURCE0} -l --ruby > rubygem-sinatra.gemspec

%build
gem build rubygem-sinatra.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sinatra-1.4.7.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/sinatra-1.4.7
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/sinatra-1.4.7.gem
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/AUTHORS.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.de.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.es.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.fr.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.hu.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.ja.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.ko.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.pt-br.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.pt-pt.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.ru.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/README.zh.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/examples/chat.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/examples/simple.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/examples/stream.ru
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/images/404.png
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/images/500.png
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/main.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/sinatra.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/asciidoctor_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/base_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/builder_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/coffee_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/compile_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/contest.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/creole_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/delegator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/encoding_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/erb_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/extensions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/haml_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/helpers_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/integration/app.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/integration_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/integration_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/less_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/liquid_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/mapped_error_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/markaby_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/markdown_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/mediawiki_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/middleware_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/nokogiri_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/public/favicon.ico
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/public/hello+world.txt
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/rabl_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/rack_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/radius_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/rdoc_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/readme_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/request_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/response_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/result_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/route_added_hook_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/routing_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/sass_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/scss_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/server_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/settings_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/sinatra_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/slim_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/static_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/streaming_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/stylus_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/templates_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/textile_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/a/in_a.str
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/ascii.erb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/b/in_b.str
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/calc.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/error.builder
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/error.erb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/error.haml
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/error.sass
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/explicitly_nested.str
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/foo/hello.test
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.asciidoc
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.builder
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.coffee
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.creole
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.erb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.haml
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.less
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.liquid
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.mab
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.md
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.mediawiki
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.nokogiri
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.rabl
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.radius
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.sass
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.scss
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.slim
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.str
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.styl
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.test
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.textile
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.wlang
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/hello.yajl
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.builder
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.erb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.haml
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.liquid
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.mab
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.nokogiri
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.rabl
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.radius
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.slim
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.str
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.test
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/layout2.wlang
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/nested.str
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/views/utf8.erb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/wlang_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/sinatra-1.4.7/test/yajl_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/sinatra-1.4.7.gemspec
